name: Nintendo + Metacritic Runner

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'

jobs:
  nintendo-script:
    runs-on: ubuntu-latest
    name: Nintendo Script

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run script 1 – generate matched_nintendo_games.json
        run: node us_eu_match.js

      - name: Run script 2 – convert to XLSX
        run: node generate_converted_report.js

      - name: Upload JSON output
        uses: actions/upload-artifact@v4
        with:
          name: matched_nintendo_games_json
          path: matched_nintendo_games.json

      - name: Upload XLSX report
        uses: actions/upload-artifact@v4
        with:
          name: converted_report
          path: converted_report3.xlsx

  metacritic-enrich:
    name: Metacritic JAR Runner
    runs-on: ubuntu-latest
    needs: nintendo-script  # Will only run if nintendo-script succeeds

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download XLSX artifact
        uses: actions/download-artifact@v4
        with:
          name: converted_report
          path: .

      - name: Download JSON artifact
        uses: actions/download-artifact@v4
        with:
          name: matched_nintendo_games_json
          path: .

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Create GCP credentials file
        run: echo "${{ secrets.GCP_JSON_KEY }}" > gcp_key.json

      - name: Run Metacritic enrichment JAR
        run: java -jar metacritic_enrich_switch.jar

      - name: Commit and push updated csvjson files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git clone https://x-access-token:${{ secrets.MY_TOKEN }}@github.com/maysaleba/maysaleba.github.io.git site-repo
          cp csvjson.json site-repo/src/csvjson.json
          cp csvjson.csv site-repo/src/csvjson.csv
          cd site-repo
          git add src/csvjson.*
          git commit -m "🔁 Auto-update CSVJSON from JAR"
          git push
