name: Metacritic JAR Runner

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Nintendo Script Runner"]
    types: [completed]

jobs:
  run-jar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo (contains JAR + converted_report3.xlsx)
        uses: actions/checkout@v3

      - name: Download csvjson.json and csvjson.csv from maysaleba.github.io
        run: |
          mkdir -p site/src
          curl -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
               -o site/src/csvjson.json \
               https://raw.githubusercontent.com/maysaleba/maysaleba.github.io/main/src/csvjson.json

          curl -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
               -o site/src/csvjson.csv \
               https://raw.githubusercontent.com/maysaleba/maysaleba.github.io/main/src/csvjson.csv

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Create GCP credentials file
        run: echo "${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}" | base64 -d > gcp_key.json

      - name: Check JSON file content
        run: |
          echo "===== gcp_key.json start ====="
          cat gcp_key.json
          echo "===== gcp_key.json end ====="

      - name: Run Metacritic enrichment JAR
        run: java -jar metacritic-enrich-switch-1.0.0.jar

      - name: Commit and push updated csvjson files
        run: |
          cd site
          git init
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote add origin https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/maysaleba/maysaleba.github.io.git
          git fetch origin main
          git checkout -b main
          git add src/csvjson.*
          git commit -m "🔁 Auto-update CSVJSON from JAR"
          git push origin main
