name: Metacritic JAR Runner

on:
  workflow_dispatch:       # 🔹 allow manual runs from GitHub UI
  workflow_run:
    workflows: ["Nintendo Script Runner"]
    types: [completed]     # 🔹 also allow automatic trigger after the first script

jobs:
  run-jar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download XLSX artifact from previous workflow
        uses: actions/download-artifact@v4
        with:
          name: converted_report
          path: .

      - name: Download JSON artifact from previous workflow
        uses: actions/download-artifact@v4
        with:
          name: matched_nintendo_games_json
          path: .

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'  # Change to 21 or 11 if needed

      - name: Create GCP credentials file
        run: echo "${{ secrets.GCP_JSON_KEY }}" > gcp_key.json

      - name: Run Metacritic enrichment JAR
        run: java -jar metacritic_enrich_switch.jar

      - name: Commit and push updated csvjson files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git clone https://x-access-token:${{ secrets.MY_TOKEN }}@github.com/maysaleba/maysaleba.github.io.git site-repo
          cp csvjson.json site-repo/src/csvjson.json
          cp csvjson.csv site-repo/src/csvjson.csv
          cd site-repo
          git add src/csvjson.*
          git commit -m "🔁 Auto-update CSVJSON from JAR"
          git push
